# Generated by Django 2.1.7 on 2019-04-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Request',
        ),
    ]
