# Generated by Django 2.1.7 on 2019-04-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20190415_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Special_request',
            new_name='special_request',
        ),
    ]
