# Generated by Django 2.2 on 2019-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20190416_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1p', 'Single Room'), ('1p_View', 'Single Room with View'), ('2p', 'Double Room'), ('2p_View', 'Double Room with View'), ('Suite', 'Suite 3Pers'), ('Suite_ VIP', 'VIP Suite 5Pers')], max_length=20),
        ),
    ]
